# Generated by Django 4.1.1 on 2023-03-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0003_whishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredinstructor',
            name='instructor_image',
            field=models.ImageField(default=0, unique=True, upload_to='profile_ins/'),
        ),
        migrations.AddField(
            model_name='registeredstudent',
            name='student_image',
            field=models.ImageField(default=0, unique=True, upload_to='profile_stu/'),
        ),
    ]
