# Generated by Django 4.1.1 on 2023-03-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0005_remove_registeredstudent_student_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default='', unique=True, upload_to='course_image/'),
        ),
        migrations.AlterField(
            model_name='registeredinstructor',
            name='instructor_image',
            field=models.ImageField(default='', unique=True, upload_to='profile_image/'),
        ),
    ]
