# Generated by Django 4.1.1 on 2023-03-29 05:52

from django.db import migrations, models
import yogaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0007_registeredstudent_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default='', unique=True, upload_to='course_image/', validators=[yogaapp.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='registeredinstructor',
            name='instructor_image',
            field=models.ImageField(default='', unique=True, upload_to='profile_image/', validators=[yogaapp.models.validate_image_file, yogaapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='student_image',
            field=models.ImageField(default='', unique=True, upload_to='profile_image/', validators=[yogaapp.models.validate_image_file]),
        ),
    ]
