# Generated by Django 4.1.1 on 2023-03-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0009_courses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredinstructor',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
