# Generated by Django 4.1.1 on 2023-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0012_alter_feedback_course_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
