# Generated by Django 4.1.1 on 2023-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0014_alter_courses_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(),
        ),
    ]
