# Generated by Django 4.1.1 on 2023-04-15 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0016_alter_courses_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.registeredstudent')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.videos')),
            ],
        ),
    ]
