# Generated by Django 4.1.1 on 2023-03-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yogaapp', '0002_payment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPoseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.registeredinstructor')),
            ],
        ),
    ]
