# Generated by Django 4.1.1 on 2023-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posecollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaposedata',
            name='audio_file',
            field=models.FileField(default='', upload_to='audio/'),
        ),
    ]
