# Generated by Django 4.1.1 on 2023-03-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0004_registeredinstructor_instructor_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredstudent',
            name='student_image',
        ),
        migrations.AlterField(
            model_name='registeredinstructor',
            name='instructor_image',
            field=models.ImageField(default=0, unique=True, upload_to='profile_image/'),
        ),
    ]
