# Generated by Django 4.1.1 on 2023-04-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0011_coursepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.courses'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.registeredstudent'),
        ),
    ]
