# Generated by Django 4.1.1 on 2023-04-07 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0013_alter_courses_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 4, 7)),
        ),
    ]
