# Generated by Django 4.1.1 on 2023-04-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0017_daily_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.registeredstudent')),
            ],
        ),
    ]
