# Generated by Django 4.1.1 on 2023-04-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0019_instructorsalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allotted', models.PositiveIntegerField(default=0)),
                ('date_allotted', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='InstructorSalary',
        ),
    ]
