# Generated by Django 4.1.1 on 2023-04-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0020_salaryallotment_delete_instructorsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.FloatField(default=0.18),
        ),
    ]
