# Generated by Django 4.1.1 on 2023-03-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_classschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Ended', 'Ended')], default='Upcoming', max_length=20),
        ),
    ]
