# Generated by Django 4.1.1 on 2023-03-31 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_alter_classschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
