# Generated by Django 4.1.1 on 2023-03-31 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0011_coursepurchase'),
        ('schedule', '0006_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='students',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='course_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yogaapp.coursepurchase'),
        ),
    ]
