# Generated by Django 4.1.1 on 2023-04-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default='Absent', max_length=10),
        ),
    ]
