# Generated by Django 4.1.1 on 2023-04-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_attendance_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present')], default='ABSENT', max_length=10),
        ),
    ]
