# Generated by Django 4.1.1 on 2023-04-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0011_coursepurchase'),
        ('schedule', '0013_alter_classschedule_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.courses'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
