# Generated by Django 4.1.1 on 2023-03-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0010_registeredinstructor_bio'),
        ('schedule', '0004_classschedule_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='students',
            field=models.ManyToManyField(blank=True, to='yogaapp.registeredstudent'),
        ),
    ]
