# Generated by Django 4.1.1 on 2023-03-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_classschedule_students_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
