# Generated by Django 4.1.1 on 2023-04-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0011_coursepurchase'),
        ('schedule', '0011_alter_attendance_is_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaapp.registeredstudent')),
            ],
        ),
    ]
